[workspace]
members = ["crates/teeforge", "xtask"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "GPL-3.0-or-later"
rust-version = "1.85"

[workspace.dependencies]
base64 = "0.22.1"
libc = "0.2.189"
sha2 = "0.10.9"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
